steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'us-east1-docker.pkg.dev/$PROJECT_ID/digi-cart/digi-cart-platform-ui:latest']
    allowFailure: true
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/digi-cart/digi-cart-platform-ui:latest'
      - '--cache-from'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/digi-cart/digi-cart-platform-ui:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://digi-cart-api-gateway.us-east1.run.app/api'
      - '--build-arg'
      - 'NEXT_PUBLIC_STOREFRONT_URL=https://digi-cart-storefront.run.app'
      - '.'
    dir: 'ui/platform-ui'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/digi-cart/digi-cart-platform-ui:latest']
images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/digi-cart/digi-cart-platform-ui:latest'
